# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - master
      - feature/*
      - hotfix/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    black-and-isort:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version:
                    - 3.x
        timeout-minutes: 60

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.BRANCH }}

            - name: Prerequisite
              run: |
                  pip3 install --upgrade pip setuptools
                  pip3 install black --no-cache --user
                  pip3 install isort --no-cache --user

            - name: apply isort
              run: python3 -m isort .

            - name: apply black
              run: python3 -m black .

            - name: commit & push
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"                                    
                  git add -A && git diff-index --cached --quiet HEAD || git commit -m 'style: isort/black'
                  git push

            - name: Slack-Notification
              uses: 8398a7/action-slack@v3
              with:
                  status: ${{job.status}}
                  fields: repo,message,commit,author,action,eventName,ref,workflow
                  author_name: Lint Notification
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
              if: failure()
